version: '2'
services:
    trouvetonprof-app:
        image: trouvetonprof
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://trouvetonprof-mariadb:3306/trouvetonprof
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trouvetonprof-mariadb:
        extends:
            file: mariadb.yml
            service: trouvetonprof-mariadb
